export const constants = {
    iAwareEnglishPagesNames: [
        { id: 'Users', name: 'Users' },
        { id: 'TenantGroups', name: 'Tenant Groups' },
        { id: 'TenantUnit', name: 'Tenant Unit' },
        { id: 'PointingSystem', name: 'Pointing System' },
        { id: 'Role', name: 'Role' },
        { id: 'TenantSettings', name: 'Tenant Settings' },
        { id: 'Badge', name: 'Badge' },
        { id: 'Campaign', name: 'Campaign' },
        { id: 'CampaignManagement', name: 'Campaign Management' },
        { id: 'EmailDomains', name: 'Email Domains' },
        { id: 'Languages', name: 'Languages' },
        { id: 'NotificationSettings', name: 'Notification Settings' },
        { id: 'PageManagement', name: 'Page Management' },
        { id: 'PhishingCategory', name: 'Phishing Category' },
        { id: 'PhishingEmailTemplates', name: 'Phishing Email Templates' },
        { id: 'SecurityTraining', name: 'Security Training' },
        { id: 'Subscription', name: 'Subscription' },
        { id: 'SupportCategory', name: 'Support Category' },
        { id: 'SupportSubject', name: 'Support Subject' },
        { id: 'SupportStatus', name: 'Support Status' },
        { id: 'SupportTapMenue', name: 'Support Tap Menue' },
        { id: 'iAwarePortal', name: 'iAware Portal' },
        { id: 'TenantAdminPortal', name: 'Tenant Admin Portal' },
        { id: 'TenantUserPortal', name: 'Tenant User Portal' },
        { id: 'PaymentReminder', name: 'Payment Reminder' },
        { id: 'TrainingLessonCateogry', name: 'Training Lesson Cateogry' },
        { id: 'LibraryBackground', name: 'Library Background' },
        { id: 'LibraryCharacter', name: 'Library Character' },
        { id: 'LibraryQuote', name: 'Library Quote' },
        { id: 'LibraryWallpaper', name: 'Library Wallpaper' },
        { id: 'AppMenueProfile', name: 'App Menue Profile' },
        { id: 'AppLayout', name: 'App Layout' },
        { id: 'LibraryWallpaperLanguage', name: 'Library Wallpaper Language' },
        { id: 'IAwareAdminDashboard', name: 'iAware Admin Dashboard' },
        { id: 'UserDashboard', name: 'User Dashboard' },
        { id: 'Leaderboard', name: 'Leaderboard' },
        { id: 'Gamification', name: 'Gamification' },
        { id: 'Invoice', name: 'Invoice' },
        { id: 'TrainingCampaigns', name: 'Training Campaigns' },
        { id: 'PhishingCampaigns', name: 'Phishing Campaigns' },
        { id: 'MultimediaLibrary', name: 'Multimedia Library' },
        { id: 'Industry', name: 'Industry' },

        { id: 'Apps', name: 'Apps' },
        { id: 'UIKit', name: 'UI Kit' },
        { id: 'PrimeBlocks', name: 'Prime Blocks' },
        { id: 'Utilities', name: 'Utilities' },
        { id: 'Pages', name: 'Pages' },
        { id: 'ECommerce', name: 'E-Commerce' },
        { id: 'Hierarchy', name: 'Hierarchy' },
        { id: 'Start', name: 'Start' },
    ],

    iAwareArabicPagesNames: [
        { id: 'Users', name: 'المستخدمين' },
        { id: 'TenantGroups', name: 'المجموعات' },
        { id: 'TenantUnit', name: 'الاقسام' },
        { id: 'PointingSystem', name: 'نظام النقاط العالمى' },
        { id: 'Role', name: 'الصلاحيات' },
        { id: 'TenantSettings', name: 'الاعدادات' },
        { id: 'Badge', name: 'الشارات' },
        { id: 'Campaign', name: 'الحملة' },
        { id: 'CurrentCampaign', name: 'الحملة الحالية' },
        { id: 'CampaignManagement', name: 'ادارة الحملة' },
        { id: 'EmailDomains', name: 'نطاقات البريد الإلكتروني' },
        { id: 'Languages', name: 'اللغات' },
        { id: 'NotificationSettings', name: 'اعدادات الاشعارات' },
        { id: 'PageManagement', name: 'ادارة الصفحات' },
        { id: 'PhishingCategory', name: 'فئة التصيد الاحتيالي' },
        { id: 'PhishingEmailTemplates', name: 'قوالب رسائل البريد الإلكتروني الاحتيالية' },
        { id: 'SecurityTraining', name: 'التدريب الأمني' },
        { id: 'Subscription', name: 'ادارة الاشتراك' },
        { id: 'SupportCategory', name: 'فئة الدعم' },
        { id: 'SupportSubject', name: 'موضوع الدعم' },
        { id: 'SupportStatus', name: 'حالة الدعم' },
        { id: 'SupportTapMenue', name: 'دعم قائمة النقر' },
        { id: 'iAwarePortal', name: 'بوابة iAware' },
        { id: 'TenantAdminPortal', name: 'بوابة إدارة المستأجرين' },
        { id: 'TenantUserPortal', name: 'بوابة مستخدم المستأجر' },
        { id: 'PaymentReminder', name: 'تذكير الدفع' },
        { id: 'TrainingLessonCateogry', name: 'فئة الدرس التدريبي' },
        { id: 'LibraryBackground', name: 'خلفية المكتبة' },
        { id: 'LibraryCharacter', name: 'مكتبة الشخصيات' },
        { id: 'LibraryQuote', name: 'اقتباسات المكتبة' },
        { id: 'LibraryWallpaper', name: 'خلفية المكتبة' },
        { id: 'AppMenueProfile', name: 'ملف تعريف قائمة التطبيق' },
        { id: 'AppLayout', name: 'تخطيط التطبيق' },
        { id: 'LibraryWallpaperLanguage', name: 'خلفية مكتبة اللغة' },
        { id: 'IAwareAdminDashboard', name: 'لوحة تحكم المسؤول' },
        { id: 'UserDashboard', name: 'لوحة تحكم المستخدم' },
        { id: 'AdminDashboard', name: 'لوحة تحكم الرئيس' },
        { id: 'Leaderboard', name: 'لوحة الصدارة' },
        { id: 'Gamification', name: 'التلعيب' },
        { id: 'Invoice', name: 'فاتورة' },
        { id: 'TrainingCampaigns', name: 'حملات التدريب' },
        { id: 'PhishingCampaigns', name: 'حملات التصيد' },
        { id: 'MultimediaLibrary', name: 'مكتبة الوسائط المتعددة' },
        { id: 'Industry', name: '؟' },

        { id: 'Apps', name: 'التطبيقات' },
        { id: 'UIKit', name: 'مجموعة أدوات واجهة المستخدم' },
        { id: 'PrimeBlocks', name: 'الكتل الأولية' },
        { id: 'Utilities', name: 'المرافق' },
        { id: 'Pages', name: 'الصفحات' },
        { id: 'ECommerce', name: 'التجارة الإلكترونية' },
        { id: 'Hierarchy', name: 'تَسَلسُل' },
        { id: 'Start', name: 'خلفية مكتبة اللغة' },
    ],

    iAwarePageActions: [
        { id: 'Add', name: 'Add' },
        { id: 'Edit', name: 'Edit' },
        { id: 'Delete', name: 'Delete' },
        { id: 'View', name: 'View' },
        { id: 'Active', name: 'Active' },
        { id: 'Deactive', name: 'Deactive' },
        { id: 'ExportExcelSample', name: 'Export Excel Sample' },
        { id: 'ExportExcel', name: 'Export Excel' },
        { id: 'ImportExcel', name: 'Import Excel' },
        { id: 'ViewUsers', name: 'View Users' },
        { id: 'ViewPermessions', name: 'View Permessions' },
        { id: 'Preview', name: 'Preview Template' },
        { id: 'TrainingTap', name: 'Training Tap' },
        { id: 'PhishingTap', name: 'Phishing Tap' },
        { id: 'CurrentCampaignTap', name: 'Current Campaign Tap' },
        { id: 'HistroyCampaignTap', name: 'Histroy Campaign Tap' },
        { id: 'UserProfile', name: 'User Profile' },
        { id: 'TenantProfile', name: 'Tenant Profile' },
        { id: 'Setteings', name: 'Setteings' },
        { id: 'SupportBtn', name: 'Support Button' },
        { id: 'ThemeBtn', name: 'Theme Button' },
        { id: 'SyncADUsers', name: 'Sync Active Directory Users' },
        { id: 'SyncADGroups', name: 'Sync Active Directory Groups' },
        { id: 'ForwardTicket', name: 'Forward Ticket' },
        { id: 'AllTicketsTab', name: 'All Ticket Tap' },
        { id: 'AdminDashboard', name: 'Admin Dashboard' },
        { id: 'IAwareAdminDashboard', name: 'iAware Admin Dashboard' },
        { id: 'UserDashboard', name: 'User Dashboard' },
        { id: 'Leaderboard', name: 'Leaderboard' },
        { id: 'Gamification', name: 'Gamification' },
        { id: 'Invoice', name: 'Invoice' },
        { id: 'TrainingCampaigns', name: 'Training Campaigns' },
        { id: 'PhishingCampaigns', name: 'Phishing Campaigns' },
        { id: 'Organization', name: 'Organization' },
        { id: 'Phishing', name: 'Phishing' },
        { id: 'Training', name: 'Training' },
        { id: 'Play', name: 'Play' },
        { id: 'Dashboard', name: 'Dashboard' },
        { id: 'Subscription', name: 'Subscription' },
        { id: 'ActiveDirectory', name: 'Active Directory' },
        { id: 'Administrators', name: 'Administrators' },
        { id: 'ViewCampaignDetails', name: 'View Campaign Details' },
        { id: 'AddDefaultWallpaper', name: 'Upload Default Wallpaper' },
        { id: 'DownloadScreenSavers', name: 'Download ScreenSavers' },
    ],

    pages: {
        users: 'Users',
        tenantGroup: 'TenantGroups',
        role: 'Role',
        settings: 'TenantSettings',
        badge: 'Badge',
        campaign: 'Campaign',
        currentCampaign: 'CurrentCampaign',
        campaignManagement: 'CampaignManagement',
        emailDomains: 'EmailDomains',
        language: 'Languages',
        notificationSettings: 'NotificationSettings',
        pageManagement: 'PageManagement',
        phishingCategory: 'PhishingCategory',
        phishingEmailTemplates: 'PhishingEmailTemplates',
        paymentReminder: 'PaymentReminder',
        securityTraining: 'SecurityTraining',
        trainingLessonCateogry: 'TrainingLessonCateogry',
        subscription: 'Subscription',
        supportCategory: 'SupportCategory',
        supportSubject: 'SupportSubject',
        supportStatus: 'SupportStatus',
        supportTapMenue: 'SupportTapMenue',
        iAwarePortal: 'iAwarePortal',
        tenantAdminPortal: 'TenantAdminPortal',
        tenantUserPortal: 'TenantUserPortal',
        libraryBackground: 'LibraryBackground',
        libraryCharacter: 'LibraryCharacter',
        libraryQuote: 'LibraryQuote',
        libraryWallpaper: 'LibraryWallpaper',
        appMenueProfile: 'AppMenueProfile',
        appLayout: 'AppLayout',
        libraryWallpaperLanguage: 'LibraryWallpaperLanguage',
        adminDashboard: 'AdminDashboard',
        leaderboard: 'Leaderboard',
        gamification: 'Gamification',
        invoice: 'Invoice',
        trainingCampaigns: 'TrainingCampaigns',
        phishingCampaigns: 'PhishingCampaigns',
        multimediaLibrary: 'MultimediaLibrary',
        blogCategory: 'blogCategory',
        newsCategory: 'newsCategory',
        blogCategoryPost: 'blogCategoryPost',
        newsCategoryArticle: 'newsCategoryArticle',
        tenantUnit:"TenantUnit",
        pointingSystem:"PointingSystem",
        industry:"Industry",
        apps: 'Apps',
        uIKit: 'UIKit',
        primeBlocks: 'PrimeBlocks',
        utilities: 'Utilities',
        pages: 'Pages',
        eCommerce: 'ECommerce',
        hierarchy: 'Hierarchy',
        start: 'Start',

    },

    pageActions: {
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        view: 'View',
        active: 'Active',
        deactive: 'Deactive',
        exportExcelSample: 'ExportExcelSample',
        exportExcel: 'ExportExcel',
        importExcel: 'ImportExcel',
        viewUsers: 'ViewUsers',
        viewPermessions: 'ViewPermessions',
        previewTemplate: 'Preview',
        trainingTap: 'TrainingTap',
        phishingTap: 'PhishingTap',
        currentCampaignTap: 'CurrentCampaignTap',
        histroyCampaignTap: 'HistroyCampaignTap',
        userProfile: 'UserProfile',
        tenantProfile: 'TenantProfile',
        setteings: 'Setteings',
        supportBtn: 'SupportBtn',
        themeBtn: 'ThemeBtn',
        syncADUsers: 'SyncADUsers',
        syncADGroups: 'SyncADGroups',
        forwardTicketBtn: 'ForwardTicket',
        allTicketsTab: 'AllTicketsTab',
        organization: 'Organization',
        phishing: 'Phishing',
        training: 'Training',
        play: 'Play',
        dashboard: 'Dashboard',
        iAwareAdminDashboard: 'IAwareAdminDashboard',
        userDashboard: 'UserDashboard',
        subscription: 'Subscription',
        ad: 'ActiveDirectory',
        administrators: 'Administrators',
        viewCampaignDetails: 'ViewCampaignDetails',
        addDefaultWallpaper: 'AddDefaultWallpaper',
        downlaodScreenSavers: 'DownloadScreenSavers',
        ticketStatus: 'TicketStatus',
    },
    usernameRegex: /^[a-zA-Z0-9._-]{3,256}$/,
};